<rdf:RDF
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:ot="http://www.opentox.org/api/1.2#"
xmlns:owl="http://www.w3.org/2002/07/owl#"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
<owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/date"/>
<owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/title"/>
<ot:Task rdf:about="http://localhost:8080/toxbank/task/f8726f32-36c7-4c35-8a0d-42b6fed70e80">
<ot:resultURI rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>http://localhost:8080/toxbank/task/f8726f32-36c7-4c35-8a0d-42b6fed70e80</ot:resultURI>
<ot:error>
<ot:ErrorReport>
<ot:errorCause rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>java.lang.NullPointerException&#xD;
at org.toxbank.rest.user.DBUser.&lt;init&gt;(DBUser.java:91)&#xD;
at org.toxbank.rest.protocol.CallableProtocolUpload.create(CallableProtocolUpload.java:206)&#xD;
at org.toxbank.rest.protocol.CallableProtocolUpload.doCall(CallableProtocolUpload.java:115)&#xD;
at net.idea.restnet.c.task.CallableProtectedTask.call(CallableProtectedTask.java:39)&#xD;
at net.idea.restnet.c.task.CallableProtectedTask.call(CallableProtectedTask.java:9)&#xD;
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)&#xD;
at java.util.concurrent.FutureTask.run(FutureTask.java:138)&#xD;
at net.idea.restnet.c.task.ExecutableTask.run(ExecutableTask.java:74)&#xD;
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)&#xD;
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)&#xD;
at java.util.concurrent.FutureTask.run(FutureTask.java:138)&#xD;
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)&#xD;
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)&#xD;
at java.lang.Thread.run(Thread.java:662)&#xD;
</ot:errorCause>
<ot:errorDetails rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>The server encountered an unexpected condition which prevented it from fulfilling the request</ot:errorDetails>
<ot:message rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>The server encountered an unexpected condition which prevented it from fulfilling the request</ot:message>
<ot:errorCode rdf:datatype="http://www.w3.org/2001/XMLSchema#long"
>500</ot:errorCode>
</ot:ErrorReport>
</ot:error>
<ot:hasStatus rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>Error</ot:hasStatus>
<dc:date rdf:datatype="http://www.w3.org/2001/XMLSchema#long"
>1360092101859</dc:date>
<dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
>Apply </dc:title>
</ot:Task>
</rdf:RDF>